### ISSUE TITLE
AttributeError: module 'counterpartylib.lib.log' has no attribute 'set_logger'

### ISSUE THREAD

**Issue by koustubh25** [CounterpartyXCP/counterparty-cli#121]
This error might be similar to this one https://github.com/CounterpartyXCP/counterparty-cli/issues/81 , but is slightly different. I would like to write down the steps to reproduce this error.

OS: Ubuntu 16.04
bitcoin-cli: git tag: 1.1.3

```
git fetch origin refs/tags/1.1.3
git checkout tags/1.1.3 -b 1.1.3
$ cd counterparty-cli
$ sudo pip3 install --upgrade -r requirements.txt
```
At this point, I got this error

```
counterparty-cli 1.1.3 has requirement requests==2.10.0, but you'll have requests 2.19.1 which is incompatible.
```
So, I ran the following command:
```
sudo pip3 install requests==2.10.0
```
After that, I try the below command and get an error:
```
$ sudo python3 setup.py install
```
Error:
```
  File "/home/indiesquare/counterparty-cli/counterpartycli/setup.py", line 142, in generate_config_files
    from counterpartycli.server import CONFIG_ARGS as SERVER_CONFIG_ARGS
  File "/home/indiesquare/counterparty-cli/counterpartycli/server.py", line 10, in <module>
    log.set_logger(logger)
AttributeError: module 'counterpartylib.lib.log' has no attribute 'set_logger'
```
Is there any other working branch or a workaround for this?

**Comment by chiguireitor** [comment]
There's the 1.1.4 tag on master which should be stable, and then there's the develop branch which should only be used with the corresponding develop branch on counterparty-lib. Try 1.1.4 before trying it out with the develop branch and let us know the result.

**Comment by koustubh25** [comment]
@chiguireitor 
I got the exact same error with `1.1.4` tag on `counterparty-cli`
I am using the tag `v9.54.0` on `counteryparty-lib`

**Comment by chiguireitor** [comment]
Hmmm 9.54 is quite old, have you tried using the latest 9.55 ?

**Comment by koustubh25** [comment]
Did not realize there is a later version `9.55` (does not start with a `v`). 
This works well. Thanks

**Comment by chiguireitor** [comment]
Excellent! Yeah, cli and lib versions aren't really mix and match, they go hand in hand with each other (they will eventually merge, when we get time*tm*)
