### ISSUE TITLE
get_running_info doesn't exist

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#14]
From: https://github.com/CounterpartyXCP/Documentation/blob/master/CLI/counterparty-cli.md
`* Check the status of the server with: $ counterparty-client get_running_info`

But that action is invalid.
```
counterparty-client: error: argument action: invalid choice: 'get_running_info' (choose from 'send', 'order', 'btcpay', 'issuance', 'broadcast', 'bet', 'dividend', 'burn', 'cancel', 'rps', 'rpsresolve', 'publish', 'execute', 'destroy', 'balances', 'asset', 'wallet', 'pending', 'market')
```

**Comment by ouziel-slama** [comment]
I just checked and works, you may try with latest commits.
