### ISSUE TITLE
Client doesn't handle well UTF8 

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#18]
* Win 7 
* 1.0.0RC5

I think the below was caused by UTF8 encoding of the config file. I did make some changes and also saved it as ANSI, after that it worked, so I'm not 100% sure.

```
C:\Python34\Scripts>counterparty-server start
[INFO] Running v1.0.0 of counterparty-server.
Traceback (most recent call last):
  File "C:\Python34\Scripts\counterparty-server-script.py", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0rc5', 'console_scripts', 'counterparty-server')()
  File "C:\Python34\lib\site-packages\counterparty_cli-1.0.0rc5-py3.4.egg\counterpartycli\__init__.py", line 14, in server_main
    server.main()
  File "C:\Python34\lib\site-packages\counterparty_cli-1.0.0rc5-py3.4.egg\counterpartycli\server.py", line 61, in main
    parser = add_config_arguments(parser, CONFIG_ARGS, 'server.conf')
  File "C:\Python34\lib\site-packages\counterparty_cli-1.0.0rc5-py3.4.egg\counterpartycli\util.py", line 113, in add_config_arguments
    configfile.read(cmd_args.config_file)
  File "C:\Python34\lib\configparser.py", line 672, in read
    self._read(fp, filename)
  File "C:\Python34\lib\configparser.py", line 993, in _read
    for lineno, line in enumerate(fp, start=1):
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 551: character maps to <undefined>
```

**Comment by adamkrellenstein** [comment]
@rippler, which files did you have to change?

**Comment by rippler** [comment]
@adamkrellenstein I don't know it was a cycle of several trials and errors. I thought it may have been a hyphen, but I'm not sure. I should have kept copies, but I wasn't sure if that was about the config file or something else, so I didn't. 

Yeah, I managed to repro: I open a good `client.conf` and save as UTF8. That's all it takes. I'm on RC6 now.

**Comment by adamkrellenstein** [comment]
It looks like there's Unicode in your config file?? If it's elsewhere, there's not much to be done... We can't reliably get rid of all of the Unicode in the project codebase. This is with a Unicode terminal?

**Comment by rippler** [comment]
I don't think that's the reason: there are no non-ASCII characters in my config file (I know because I start with a good `.conf` and just `Save As ...` =>  `UTF8`). 

I just tried 2 other things:
a) Search and replace all non-letters (= in UTF8 with = from ASCII, etc.)  and save the file (still as UTF8). This makes the problem go away
b) I went to Notepad++ and in Settings it's UTF8 without BOM (may be the default, but I'm not sure). When I change that to UTF8, then the problem goes away. So one would think "Ah, okay, then just don't use the weird UTF8 options", but...
c) In notepad.exe, if you open a good (`ASCII`) config file and save it as `UTF8` or `Unicode`, neither of the files will cooperate.

So it's not a bug we need to take care of (although we could probably read the header and alert people to save the file as ASCII). In general I like UTF8, but it seems to be causing troubles in both Linux and Windows.

**Comment by adamkrellenstein** [comment]
We can't guarantee that all files will be ASCII-only (this isn't 1985). If there's something else to be done, we can do that, though.

**Comment by ouziel-slama** [comment]
see this commit: https://github.com/CounterpartyXCP/counterparty-cli/commit/b14de12f782ae628b168652e2737d73fc35b1859
configuration files should be in UTF8 (with or without BOM), because yeah, this isn't 1985 ;-)

**Comment by adamkrellenstein** [comment]
Nice fix, @ouziel-slama!
