### ISSUE TITLE
Missing package...json

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-cli#20]
As for the standalone binaries (this one https://github.com/CounterpartyXCP/counterparty-cli/releases/tag/v1.0.0 ?? ). It complains about a missing package...json file. I have to first git and install the python counterparty-cli tools and run that once. Only then can I run the standalone libraries at https://github.com/CounterpartyXCP/counterparty-cli/releases/tag/v1.0.0

**Comment by mtbitcoin** [comment]
Just to follow up this issue applies only for c:\C:\counterparty-cli-win32-1.0.0\counterparty-client.exe

**Comment by ouziel-slama** [comment]
Not reproducible with the last version. Feel free to re-open if occurs again.
