### ISSUE TITLE
Better Handle Installs with `sudo`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-cli#21]
The automatic generation of the configuration file doesn't work as expected if `counterparty-cli` in installed with `sudo` (the config files are placed in `/root/`).

> another option is to do something like (untested): `os.environ['XDG_CONFIG_HOME'] = os.path.expanduser("~%s/.config" % os.environ.get('SUDO_USER', ''))` (edited)

> then use appdirs.user_config_dir and it should work with sudo

> but only do this for non mac/non windows. on nix, this should preserve the existing functionality, even when sudo is in use (and work if sudo is not in use, as well) (edited)

**Comment by ouziel-slama** [comment]
given these: https://github.com/CounterpartyXCP/Documentation/pull/42
If the use of `sudo` is a bad practice, there is no reason to handle it IMHO.
