### ISSUE TITLE
Built-in tx signing with call to Python 2 pybitcointools command is kludgy and unreliable

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-cli#28]
Moved from here: https://github.com/CounterpartyXCP/counterpartyd/issues/182

**Comment by ouziel-slama** [comment]
I think we should use `pycoin`: https://github.com/richardkiss/pycoin

**Comment by adamkrellenstein** [comment]
@ouziel-slama: sure!

**Comment by ouziel-slama** [comment]
done
