### ISSUE TITLE
Scripts need .py exension

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#9]
Just as a reminder (I'm not sure if this is being addressed elsewhere, if yes, feel free to close), on Windows can you rename `counterparty-[client,server]`to `counterparty-[client,server].py` so that they can be executed from Windows without explicitly using `python.exe`.

**Comment by ouziel-slama** [comment]
fixed here: https://github.com/CounterpartyXCP/counterparty-cli/commit/17fc7e1eed43c82d770aaee5916e16861806e489
