### ISSUE TITLE
Import error building undefined symbole _PyUnicode_CheckConsistency on Gentoo linux

### ISSUE THREAD

**Issue by 1credit** [CounterpartyXCP/counterparty-cli#90]
Counterparty_lib built fine.  Cli pip3 step worked fine.

python3 setup.py install fails with:

http://puu.sh/qEPBj/e333b3f02f.png

Running a gentoo based linux system that is up-to-date with all packages.  Feels like I'm missing one however...

**Comment by unsystemizer** [comment]
See https://bugs.python.org/issue23108
It looks like an upstream issue.

**Comment by unsystemizer** [comment]
It's been fixed in upstream repo.
This should be closed.
